# Generated by Django 6.0.6 on 2026-06-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, unique=True, verbose_name='Chat ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guruh/Kanal Nomi')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'Faol Chat',
                'verbose_name_plural': 'Faol Chatlar',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=100, verbose_name='Qayerdan')),
                ('to_city', models.CharField(max_length=100, verbose_name='Qayerga')),
                ('departure_date', models.DateField(verbose_name='Qachon (Sana)')),
                ('price', models.CharField(max_length=50, verbose_name='Narxi')),
                ('phone', models.CharField(max_length=20, verbose_name='Murojaat uchun tel raqam')),
                ('telegram_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Username')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha izoh")),
                ('is_published', models.BooleanField(default=False, verbose_name='Yuborildi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': "E'lon (Chipta)",
                'verbose_name_plural': "E'lonlar (Chiptalar)",
            },
        ),
    ]
