# Generated by Django 6.0.6 on 2026-06-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovServiceAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, verbose_name='Xizmat nomi')),
                ('ministry', models.CharField(max_length=200, verbose_name='Idora / Vazirlik')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('working_hours', models.CharField(help_text='Masalan: Du–Ju 09:00–18:00', max_length=100, verbose_name='Ish vaqti')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('website', models.URLField(blank=True, help_text='Ixtiyoriy', null=True, verbose_name='Veb-sayt')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gov_services/', verbose_name='Rasm (ixtiyoriy)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Yuborildi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': "Davlat Xizmati E'loni",
                'verbose_name_plural': "Davlat Xizmatlari E'lonlari",
            },
        ),
        migrations.CreateModel(
            name='JobAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='Lavozim nomi')),
                ('company', models.CharField(max_length=200, verbose_name='Kompaniya / Ish beruvchi')),
                ('employment_type', models.CharField(choices=[('full_time', "To'liq stavka"), ('part_time', 'Qisman stavka'), ('remote', 'Masofadan'), ('contract', 'Shartnoma asosida'), ('internship', 'Amaliyot (Staj)')], default='full_time', max_length=20, verbose_name='Ish turi')),
                ('salary', models.CharField(blank=True, help_text='Ixtiyoriy. Masalan: 3 000 000 – 5 000 000 UZS', max_length=100, null=True, verbose_name='Maosh')),
                ('location', models.CharField(max_length=200, verbose_name='Joylashuv / Shahar')),
                ('requirements', models.TextField(verbose_name='Talablar va vazifalar')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('telegram_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram username')),
                ('deadline', models.DateField(blank=True, help_text='Ixtiyoriy', null=True, verbose_name='Ariza topshirish muddati')),
                ('image', models.ImageField(blank=True, null=True, upload_to='jobs/', verbose_name='Banner / Logotip (ixtiyoriy)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Yuborildi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': "Ish O'rin E'loni",
                'verbose_name_plural': "Ish O'rin E'lonlari",
            },
        ),
        migrations.CreateModel(
            name='ProductAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('category', models.CharField(help_text='Masalan: Elektronika, Kiyim, Mebel …', max_length=100, verbose_name='Toifa')),
                ('condition', models.CharField(choices=[('new', 'Yangi'), ('used', 'Ishlatilgan'), ('like_new', 'Yangiday')], default='new', max_length=20, verbose_name='Holati')),
                ('price', models.CharField(max_length=50, verbose_name='Narxi')),
                ('location', models.CharField(max_length=200, verbose_name='Joylashuv / Shahar')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('telegram_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram username')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Rasm')),
                ('is_published', models.BooleanField(default=False, verbose_name='Yuborildi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': "Mahsulot E'loni",
                'verbose_name_plural': "Mahsulot E'lonlari",
            },
        ),
    ]
