# Generated by Django 6.0.6 on 2026-06-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0002_govserviceannouncement_jobannouncement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Xabar matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='simple_messages/', verbose_name='Rasm (ixtiyoriy)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Yuborildi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Oddiy Xabar',
                'verbose_name_plural': 'Oddiy Xabarlar',
            },
        ),
    ]
